name: SonarCloud

on:
  push:
    branches:
      - main
      - master

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.organization=Cdavidjara-org
            -Dsonar.projectKey=Cdavidjara_Seguros
            -Dsonar.token=${{ secrets.SONAR_TOKEN }}
            -Dsonar.sources=.
